name: Windows Build

on:
  workflow_dispatch:
  push:
    paths:
      - backendHelen/**
      - helen/**
      - Hellen_model_RN/**
      - packaging/**

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r packaging/requirements-win.txt

      - name: Build executable with PyInstaller
        shell: pwsh
        run: |
          python -m PyInstaller --clean --noconfirm packaging/helen_backend.spec

      - name: Install Inno Setup
        shell: pwsh
        run: |
          choco install innosetup --yes

      - name: Build Windows installer
        shell: pwsh
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" packaging\inno_setup.iss

      - name: Camera diagnostic
        shell: pwsh
        run: |
          python -m backendHelen.diagnostics --allow-missing

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: helen-windows-build
          path: |
            dist/helen-backend
            dist/Setup Helen.exe
